### ISSUE TITLE
Infantry subcell bug

### ISSUE THREAD

**Issue by handama** [revengenowstudio/YR_RN_Mission_Editor#10]
In game, infantry will take subcell 2,3,4 as follow:
![20190623212040!Cellspots-ts](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/55939089/cae34507-68e1-4abb-9d8d-b5fae5774b88)
![EA8424A4E6169C27767D2D7F76F2570C](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/55939089/b37ac252-26af-4a3c-9a99-eaa65209aa82)
However, FA2 places infantries to 0 (or 1, they are the same) by default. Moreover, FA2 cannot display infantries at 4 (and cannot be edited or deleted).
![1FC873E9A2C354DD94147EBC73948F3A](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/55939089/8a4ff112-b657-4bf3-9f05-afa6a837cfd1)
More information can be seen at https://modenc.renegadeprojects.com/Cell_Spots

**Comment by handama** [comment]
in FA2 v2.0, the display of subcell 0/1 changed from center to top corner, but in Game it's still in the center
![E6619EC1F68406424D5C445E0B87BAFD](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/55939089/ae35ca61-3864-46b9-b068-71cc276bb7e5)

**Comment by Zero-Fanker** [comment]
Now you can have a try .

**Comment by handama** [comment]
> Now you can have a try .

有空一定try try）

**Comment by shuiping233** [comment]
我将使用日牛进行一个单元格的try

- 测试环境： 8ddde446 ， 复仇时刻0.99.916a3
- 测试结论：如下图所示，确实一个格子能挤得下4个人了，地编里的步兵排列循序和游戏里也是一致的。

![GIF127](https://github.com/user-attachments/assets/f15662c9-3f71-4399-83d9-1e00e9b9aadd)

地编下的样子
![image](https://github.com/user-attachments/assets/20d6dde4-c799-4a1e-bff0-6bd7957c446b)
游戏里的样子：
![image](https://github.com/user-attachments/assets/05d7b15f-ff24-4c59-8da9-2be69e48e493)

**Comment by handama** [comment]
感觉最好是维持一个格子三个人，0号subcell的可以有一个设置选择放在0号或者4号）
改一下 CMapData::AddInfantry 应该就可以
