### ISSUE TITLE
地编对覆盖物的处理存在问题

### ISSUE THREAD

**Issue by shuiping233** [revengenowstudio/YR_RN_Mission_Editor#11]
使用新地编打开并重新覆盖保存了所有特别行动地图后，对保存的内容与原本地图内容进行文本比较，结论如下：
  - 所有特别行动地图的以下三个 节 的内容均与原地图内容不一致
  - `[IsoMapPack5]`中元素的内容与原内容完全不一致
  - `[OverlayDataPack]` 中的元素内容大部分与原内容不一致，部分内容是一致的
  - `[OverlayPack]` 中的元素内容大部分与原内容不一致，部分内容是一致的

  - 以下为一些比较示例：  
    ![1717080929932](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/9affbd40-8a61-4483-ad7a-9bb310bae641)
    ![1717081140350](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/4e1f994f-ae51-4448-877e-a978a4deb747)
    ![1717081137291](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/c2a77b7f-5b2f-4027-8b51-21af927e0722)

  - 以上结果说明新地编处理覆盖物的逻辑与旧地编不一致了，而旧地编在覆盖保存原地图文件时是完全和原内容一致的

在对某张测试地图使用新地编进行覆盖保存后，放入游戏内进行测试，观察到了一个有关覆盖物的问题，新地编似乎没正确处理沙袋覆盖物 ，凭空生成了不少原地图内容中不存在的沙袋覆盖物 
    ![1717084902622](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/b8a914a7-ba2e-486b-9c11-79c813204ff1)
    ![1717084906996](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/a2a1d380-7602-41ff-880d-70c0747450a9) 
- 在新地编中未正确处理的沙袋覆盖物：
    ![1717085234713](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/561ed916-c30c-4b04-b285-20cacb7ca465)
- 在旧地编中正确处理的沙袋覆盖物：
   ![1717085283483](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/50431059-c1ac-4a40-b509-6002a44ed4da)

**Comment by shuiping233** [comment]
9cddabb 修复后测试结果：
重新使用苏军特别行动第二关进行测试，发现修复后新地编没有产生多余的沙袋覆盖物，其余区域也并未发现异常覆盖物
以下为源地图与新地编保存覆盖的地图内容对比，虽然覆盖物相关文本并不一致，但是在游戏内测试中并未发现异常覆盖物，姑且认为bug已经修复
![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/ba294d0c-970d-4c37-85b0-f9668f3bf180)
![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/8e0615ad-9882-41c5-8ff7-c7ef13861b65)

**Comment by shuiping233** [comment]
> [9cddabb](https://github.com/revengenowstudio/YR_RN_Mission_Editor/commit/9cddabbb3a4242dcc72063c2ba6c16395af9ec8b) 修复后测试结果： 重新使用苏军特别行动第二关进行测试，发现修复后新地编没有产生多余的沙袋覆盖物，其余区域也并未发现异常覆盖物 以下为源地图与新地编保存覆盖的地图内容对比，虽然覆盖物相关文本并不一致，但是在游戏内测试中并未发现异常覆盖物，姑且认为bug已经修复 ![image](https://private-user-images.githubusercontent.com/49360196/336866049-ba294d0c-970d-4c37-85b0-f9668f3bf180.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NDQ2MzcsIm5iZiI6MTcxNzY0NDMzNywicGF0aCI6Ii80OTM2MDE5Ni8zMzY4NjYwNDktYmEyOTRkMGMtOTcwZC00YzM3LTg1YjAtZjk2NjhmM2JmMTgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDAzMjUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkNTgwNjQwNTFjODUyY2U0YTc0Y2YwOTc3OGFjZDU1MDFjOTFhOTcxOTVlYzNjMmNjZTAxM2U5N2RkYTJjMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hUH0DCmsiXC0VcMF_OsltpUVo_rgKY-BhWppBKefsbA) ![image](https://private-user-images.githubusercontent.com/49360196/336866250-8e0615ad-9882-41c5-8ff7-c7ef13861b65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NDQ2MzcsIm5iZiI6MTcxNzY0NDMzNywicGF0aCI6Ii80OTM2MDE5Ni8zMzY4NjYyNTAtOGUwNjE1YWQtOTg4Mi00MWM1LThmZjctYzdlZjEzODYxYjY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDAzMjUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzZWFhNDU3MmU0NTFmMTI5ODEzZDg1MGU2ZTE5ZGQ5YzI1MDhjZjI2NzdjZGM3Y2RiOTMyNWU2NjU3N2I4ZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IDpFQyc-xqtvMSu7XZS6h_H3VsLmhZqq0hkWA52rFHw)

再补充一点测试结论：
- 新地编保存覆盖源地图后，再次使用新地编对保存覆盖的地图进行读取，仍未发现异常情况。若此基础上再次进行保存覆盖地图文件，则地图文件内容不会发生改变
- 切换到main分支x86配置编译出来的32位地编去保存覆盖了苏军特别行动第二关，发现覆盖后的OverlayDataPack和OverlayPack 与与原地图是完全一致的，但 isomappack 的内容仍然完全不一致

**Comment by Zero-Fanker** [comment]
> > [9cddabb](https://github.com/revengenowstudio/YR_RN_Mission_Editor/commit/9cddabbb3a4242dcc72063c2ba6c16395af9ec8b) 修复后测试结果： 重新使用苏军特别行动第二关进行测试，发现修复后新地编没有产生多余的沙袋覆盖物，其余区域也并未发现异常覆盖物 以下为源地图与新地编保存覆盖的地图内容对比，虽然覆盖物相关文本并不一致，但是在游戏内测试中并未发现异常覆盖物，姑且认为bug已经修复 ![image](https://private-user-images.githubusercontent.com/49360196/336866049-ba294d0c-970d-4c37-85b0-f9668f3bf180.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NDQ2MzcsIm5iZiI6MTcxNzY0NDMzNywicGF0aCI6Ii80OTM2MDE5Ni8zMzY4NjYwNDktYmEyOTRkMGMtOTcwZC00YzM3LTg1YjAtZjk2NjhmM2JmMTgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDAzMjUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkNTgwNjQwNTFjODUyY2U0YTc0Y2YwOTc3OGFjZDU1MDFjOTFhOTcxOTVlYzNjMmNjZTAxM2U5N2RkYTJjMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hUH0DCmsiXC0VcMF_OsltpUVo_rgKY-BhWppBKefsbA) ![image](https://private-user-images.githubusercontent.com/49360196/336866250-8e0615ad-9882-41c5-8ff7-c7ef13861b65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NDQ2MzcsIm5iZiI6MTcxNzY0NDMzNywicGF0aCI6Ii80OTM2MDE5Ni8zMzY4NjYyNTAtOGUwNjE1YWQtOTg4Mi00MWM1LThmZjctYzdlZjEzODYxYjY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDAzMjUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzZWFhNDU3MmU0NTFmMTI5ODEzZDg1MGU2ZTE5ZGQ5YzI1MDhjZjI2NzdjZGM3Y2RiOTMyNWU2NjU3N2I4ZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IDpFQyc-xqtvMSu7XZS6h_H3VsLmhZqq0hkWA52rFHw)
> 
> 再补充一点测试结论：
> 
> * 新地编保存覆盖源地图后，再次使用新地编对保存覆盖的地图进行读取，仍未发现异常情况。若此基础上再次进行保存覆盖地图文件，则地图文件内容不会发生改变
> * 切换到main分支并用编译出来的地编去保存覆盖了苏军特别行动第二关，发现覆盖后的OverlayDataPack和OverlayPack 与与原地图是完全一致的，但 isomappack 的内容仍然完全不一致

开一个新issue后面再调查。就描述为保存后数据不一致。

**Comment by shuiping233** [comment]
> > > [9cddabb](https://github.com/revengenowstudio/YR_RN_Mission_Editor/commit/9cddabbb3a4242dcc72063c2ba6c16395af9ec8b) 修复后测试结果： 重新使用苏军特别行动第二关进行测试，发现修复后新地编没有产生多余的沙袋覆盖物，其余区域也并未发现异常覆盖物 以下为源地图与新地编保存覆盖的地图内容对比，虽然覆盖物相关文本并不一致，但是在游戏内测试中并未发现异常覆盖物，姑且认为bug已经修复 ![image](https://private-user-images.githubusercontent.com/49360196/336866049-ba294d0c-970d-4c37-85b0-f9668f3bf180.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NDQ2MzcsIm5iZiI6MTcxNzY0NDMzNywicGF0aCI6Ii80OTM2MDE5Ni8zMzY4NjYwNDktYmEyOTRkMGMtOTcwZC00YzM3LTg1YjAtZjk2NjhmM2JmMTgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDAzMjUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkNTgwNjQwNTFjODUyY2U0YTc0Y2YwOTc3OGFjZDU1MDFjOTFhOTcxOTVlYzNjMmNjZTAxM2U5N2RkYTJjMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hUH0DCmsiXC0VcMF_OsltpUVo_rgKY-BhWppBKefsbA) ![image](https://private-user-images.githubusercontent.com/49360196/336866250-8e0615ad-9882-41c5-8ff7-c7ef13861b65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NDQ2MzcsIm5iZiI6MTcxNzY0NDMzNywicGF0aCI6Ii80OTM2MDE5Ni8zMzY4NjYyNTAtOGUwNjE1YWQtOTg4Mi00MWM1LThmZjctYzdlZjEzODYxYjY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDAzMjUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzZWFhNDU3MmU0NTFmMTI5ODEzZDg1MGU2ZTE5ZGQ5YzI1MDhjZjI2NzdjZGM3Y2RiOTMyNWU2NjU3N2I4ZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IDpFQyc-xqtvMSu7XZS6h_H3VsLmhZqq0hkWA52rFHw)
> > 
> > 
> > 再补充一点测试结论：
> > 
> > * 新地编保存覆盖源地图后，再次使用新地编对保存覆盖的地图进行读取，仍未发现异常情况。若此基础上再次进行保存覆盖地图文件，则地图文件内容不会发生改变
> > * 切换到main分支并用编译出来的地编去保存覆盖了苏军特别行动第二关，发现覆盖后的OverlayDataPack和OverlayPack 与与原地图是完全一致的，但 isomappack 的内容仍然完全不一致
> 
> 开一个新issue后面再调查。就描述为保存后数据不一致。

新issue位于 #38 ，关闭此issue
