### ISSUE TITLE
抬升/降低地表工具在大笔刷下操作地图四角会弹框

### ISSUE THREAD

**Issue by handama** [revengenowstudio/YR_RN_Mission_Editor#116]
<img width="691" alt="Snipaste_2024-11-10_23-23-21" src="https://github.com/user-attachments/assets/beeea927-b681-4921-82db-f423849f29f2">
如图，CIsoView::OnLButtonDown在这四个工具遍历笔刷范围时，没有判断单元格是否有效

**Comment by Zero-Fanker** [comment]
有思路吗？大致看了一下是一个基础函数越界的问题
