### ISSUE TITLE
"事件触发"复制功能不能正确创建并复制触发标签，导致复制的触发标签不可使用

### ISSUE THREAD

**Issue by shuiping233** [revengenowstudio/YR_RN_Mission_Editor#119]
- 测试环境： f5601fb
- 测试结论：复制触发功能在复制事件触发时可能没处理好什么东西，导致复制出来的触发标签少了两个项，且后续地编也无法修改这个复制出错误的触发标签
左侧是手动创建两个触发的结果，右侧是复制触发的结果，可见复制触发时没有正确复制触发标签的内容
![image](https://github.com/user-attachments/assets/5cabd06d-5071-4bc7-a754-caa0305e5f29)

手动创建两个触发的效果：
![image](https://github.com/user-attachments/assets/e653b74f-a8d6-4fd2-9a37-c04c2e66f93b)

复制触发后
![image](https://github.com/user-attachments/assets/a2ce60fd-ed7b-40a4-aedc-195620cfbaff)
![image](https://github.com/user-attachments/assets/3159390a-e0a2-4f5b-b806-47131cdc7e4e)

**Comment by Zero-Fanker** [comment]
事实上是数据错位了，已经在看了
