### ISSUE TITLE
道路地形没有正确读取到色盘导致渲染图像不正常

### ISSUE THREAD

**Issue by shuiping233** [revengenowstudio/YR_RN_Mission_Editor#15]
- mmsov03.map 中，道路地形渲染时似乎没有正确读取到色盘
    ![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/64d3884f-66ca-49cb-9102-abfaa428c58e)
    ![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/2feb4d8f-99cb-407c-b701-db6d143b4edc)

**Comment by Zero-Fanker** [comment]
这个是不是旧版也存在的问题？

**Comment by shuiping233** [comment]
> 这个是不是旧版也存在的问题？

已证实旧版地编确实存在此问题
![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/0ea4a4d3-fb0a-46ee-b27d-8e747b2ff963)
![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/b1b54367-0050-4711-98f4-a94f64edc638)

**Comment by shuiping233** [comment]
此问题并非由地编渲染逻辑引起，故关闭此议题
