### ISSUE TITLE
[bug]地编解码某些shp时可能引起地编崩溃

### ISSUE THREAD

**Issue by shuiping233** [revengenowstudio/YR_RN_Mission_Editor#18]
- 新地编读取mmall03.map后摄像机往左上角移动会稳定触发地编崩溃，异常发生在decode3函数中：
![1717087754930](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/80bc66f7-e153-4ba2-a68c-75d44cbccc34)
![1717087767595](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/bf3ed24d-20c5-424d-b53d-389e154ff07b)

**Comment by Zero-Fanker** [comment]
问题已证实，并且已经修复。
原因是盟军闸门的Art里设置的LoopStart并非第0帧，这段原始动画文件是有很多帧的，本身没有问题。
RN地编资源文件中用了精简版的动画，但是这个LoopStart没有改，所以产生了序号越界。现在在编辑器层面进行了防护，超出帧数时会默认只读取第0帧。

**Comment by Zero-Fanker** [comment]
该问题在RN旧版地编中应该也有，只是release下可能没有导致程序立即崩溃。
