### ISSUE TITLE
地编主窗口移动时的跟随渲染可能在某些情况下导致地编崩溃

### ISSUE THREAD

**Issue by shuiping233** [revengenowstudio/YR_RN_Mission_Editor#20]
- 我用鼠标移动了新地编的主窗口，地编窗口有一部分在屏幕可显示区域外引起可能会这个问题
  ![1716556102061](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/57cfbdfb-b035-45b9-8353-6ee556c3dbfa)

**Comment by Zero-Fanker** [comment]
如何稳定复现？我没问题啊
![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/14891010/7f8297b0-0a04-413a-b6ac-3aedba78bdb2)

**Comment by shuiping233** [comment]
> 如何稳定复现？我没问题啊 ![image](https://private-user-images.githubusercontent.com/14891010/335708652-7f8297b0-0a04-413a-b6ac-3aedba78bdb2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMzMzNDksIm5iZiI6MTcxNzIzMzA0OSwicGF0aCI6Ii8xNDg5MTAxMC8zMzU3MDg2NTItN2Y4Mjk3YjAtMGEwNC00MTNhLWI2YWMtM2FlZGJhNzhiZGIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDA5MTA0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3YjAzMjlmMGZhNTZkNGIzM2RkNGFhYTZhZTczNGVlODM4MDkxMDBhYjU1OTU0NDFiNjc4YjYwYTQ4NDAxM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WdO3chP_ptsPzZLqCc46zNQVnQrg4amBqZYqZ0lwVTA)

我找到复现方法了，议题的描述似乎不太正确，应该和小地图有关系，我录了视频演示一下

https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/69f0108a-b1c7-4ed0-9a22-e0237d86fc18


https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/da59d1f3-ddb2-452f-a1a6-9cadd6dcc3d6

**Comment by Zero-Fanker** [comment]
复现不出来。晚点看你环境

**Comment by shuiping233** [comment]
> > 如何稳定复现？我没问题啊 ![image](https://private-user-images.githubusercontent.com/14891010/335708652-7f8297b0-0a04-413a-b6ac-3aedba78bdb2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMzMzNDksIm5iZiI6MTcxNzIzMzA0OSwicGF0aCI6Ii8xNDg5MTAxMC8zMzU3MDg2NTItN2Y4Mjk3YjAtMGEwNC00MTNhLWI2YWMtM2FlZGJhNzhiZGIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDA5MTA0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3YjAzMjlmMGZhNTZkNGIzM2RkNGFhYTZhZTczNGVlODM4MDkxMDBhYjU1OTU0NDFiNjc4YjYwYTQ4NDAxM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WdO3chP_ptsPzZLqCc46zNQVnQrg4amBqZYqZ0lwVTA)
> 
> 我找到复现方法了，议题的描述似乎不太正确，应该和小地图有关系，我录了视频演示一下
> 
>  2024-06-01.17-20-50.mp4 
>  2024-06-01.17-19-35.mp4

已经证实旧地编也存在此问题  

https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/99730633-7f9c-4ff3-bd10-f984fec6ef1e

**Comment by Zero-Fanker** [comment]
已确认是FA2祖传问题。追加了一个边界检查。

**Comment by shuiping233** [comment]
- 测试环境 ： 7f6a9d2  ，新建一张单人任务地图
- 测试条件：
  - 1. 在新地图中放置任意建筑（我随手放了一个发电厂），然后使用`建立节点删除建筑`对刚刚放置于地图中的建筑使用，接着把地编主窗口（渲染了地图的部分）的一半移至屏幕外，最后使用小地图移动地编主窗口摄像机位置（小地图红框重新框中基地节点位置即可）
  - 2. 在新地图中放置任意悬崖，然后使用![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/b981b2bb-fdac-48df-8ffd-cfb012faca19)`隐藏地形快`对刚刚放置于地图中的悬崖使用，后续步骤与 `a.`条件一致，将地编主窗口部分移出屏幕外，并使用小地图操作摄像机位置
- 测试结论：经过 7f6a9d2 的修复，地编应该不会没有半透明物体的地图上发生崩溃了（测试地图为北极圈），而半透明物体相关的渲染目前仍会导致地编崩溃

- a.  

https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/42147141-02b8-4853-967c-d259c3d43bf4


- b.

https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/444e6b49-d0f8-4417-9d02-a50d0c2e59f9

**Comment by shuiping233** [comment]
- 测试环境： 6f532173
- 测试条件： 使用 #20 #26  中 提到的测试方法
- 测试结论：测试通过，6f532173 已解决半透明物体的渲染问题，已无法复现相似崩溃
