### ISSUE TITLE
增加地编不使用渐变色渲染模型的模式切换功能

### ISSUE THREAD

**Issue by shuiping233** [revengenowstudio/YR_RN_Mission_Editor#21]
- 发现不少载具未能完全渲染出所属色以至于难以分辨其所属，而即使是单位所属色是蓝色这种显眼的颜色也难以分辨其所属色，仔细观察能发现载具身上有很多紫色的部分，那些部分应该是原本要渲染成所属色的部分？
![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/af9b54c5-2edb-453f-960d-96d04d845e74)
![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/68ae5742-c776-4f53-8796-1370c203f9ed)
![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/03531ee3-97b5-4803-b3b7-51347e581fae)

**Comment by Zero-Fanker** [comment]
这个分色问题如果不是因为修改地编引起的，就不应该放这里啊

**Comment by shuiping233** [comment]
> 这个分色问题如果不是因为修改地编引起的，就不应该放这里啊

确实，在旧地编也存在分色问题，不过吧，新地编的分色问题比旧地编看着更严重，工头你怎么看
以下是旧地编的截图：
![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/0f85e9b1-5f46-4e25-b209-28895430abb8)
![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/cd5893f0-b309-4393-8e48-ff1a46de1fdc)

**Comment by Zero-Fanker** [comment]
我大致有点明白你说的情况了。但是我不排除这个是EA开源地编做出了额外调整。旧版的所属色没有做色盘的对应，但是新版做了对应，导致反而颜色不明显了。换言之更好看了，但是更不利于开发了。
![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/14891010/c0c7b4f8-febc-4f2b-871a-ef1a52d425b0)


那么我认为标题应该调整，不是没渲染出来，本质上是两个问题。RN的载具预渲染的那些素材因为早期格式转换问题损失了一些颜色。但是还引起了另一个问题，这个问题是跟本仓库有关的：因模型所属色的渲染支持了色盘对应渐变色，导致了分辨不清晰。这个问题我打算通过模仿给建筑添加轮廓的方式，给单位也添加一个轮廓描边来解决。

当然也还有另外一种简洁的方式，就是倒退，不使用渐变色。但这个最好做成功能，支持切换。

**Comment by shuiping233** [comment]
> 我大致有点明白你说的情况了。但是我不排除这个是EA开源地编做出了额外调整。旧版的所属色没有做色盘的对应，但是新版做了对应，导致反而颜色不明显了。换言之更好看了，但是更不利于开发了。 ![image](https://private-user-images.githubusercontent.com/14891010/335776559-c0c7b4f8-febc-4f2b-871a-ef1a52d425b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMTc2OTAsIm5iZiI6MTcxNzIxNzM5MCwicGF0aCI6Ii8xNDg5MTAxMC8zMzU3NzY1NTktYzBjN2I0ZjgtZmViYy00ZjJiLTg3MWEtZWYxYTUyZDQyNWIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDA0NDk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmODdiZjY3YTdkYjY1ZDgwODdhNTUyMzVmMWUyNmI2YTVmNWYxOTJmZGU1ZWU3OWRkMzE5YzcwZTVhOGU3NTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1bsPDgqPvr2n5A9TfKiSOnftKobMFDYJ_9TzydoT89s)
> 
> 那么我认为标题应该调整，不是没渲染出来，本质上是两个问题。RN的载具预渲染的那些素材因为早期格式转换问题损失了一些颜色。但是还引起了另一个问题，这个问题是跟本仓库有关的：因模型所属色的渲染支持了色盘对应渐变色，导致了分辨不清晰。这个问题我打算通过模仿给建筑添加轮廓的方式，给单位也添加一个轮廓描边来解决。
> 
> 当然也还有另外一种简洁的方式，就是倒退，不使用渐变色。但这个最好做成功能，支持切换。

我赞同工头的意见
我看见enhancement标签了，标题改成了 “[功能改进]新的模型所属色的渲染功能降低了单位所属色的可分辨程度” ，工头还有更好的标题么

**Comment by Zero-Fanker** [comment]
> > 我大致有点明白你说的情况了。但是我不排除这个是EA开源地编做出了额外调整。旧版的所属色没有做色盘的对应，但是新版做了对应，导致反而颜色不明显了。换言之更好看了，但是更不利于开发了。 ![image](https://private-user-images.githubusercontent.com/14891010/335776559-c0c7b4f8-febc-4f2b-871a-ef1a52d425b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMTc2OTAsIm5iZiI6MTcxNzIxNzM5MCwicGF0aCI6Ii8xNDg5MTAxMC8zMzU3NzY1NTktYzBjN2I0ZjgtZmViYy00ZjJiLTg3MWEtZWYxYTUyZDQyNWIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDA0NDk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmODdiZjY3YTdkYjY1ZDgwODdhNTUyMzVmMWUyNmI2YTVmNWYxOTJmZGU1ZWU3OWRkMzE5YzcwZTVhOGU3NTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1bsPDgqPvr2n5A9TfKiSOnftKobMFDYJ_9TzydoT89s)
> > 那么我认为标题应该调整，不是没渲染出来，本质上是两个问题。RN的载具预渲染的那些素材因为早期格式转换问题损失了一些颜色。但是还引起了另一个问题，这个问题是跟本仓库有关的：因模型所属色的渲染支持了色盘对应渐变色，导致了分辨不清晰。这个问题我打算通过模仿给建筑添加轮廓的方式，给单位也添加一个轮廓描边来解决。
> > 当然也还有另外一种简洁的方式，就是倒退，不使用渐变色。但这个最好做成功能，支持切换。
> 
> 我赞同工头的意见 我看见enhancement标签了，标题改成了 “[功能改进]新的模型所属色的渲染功能降低了单位所属色的可分辨程度” ，工头还有更好的标题么

已经改成配置控制了。后面再用运行时的控件来控制。开个新的issue，这个关掉。

**Comment by shuiping233** [comment]
新issue位于 #39 ，关闭此issue
