### ISSUE TITLE
放置路径点后并未对路径点列表中重新按照路径点标号升序进行排列

### ISSUE THREAD

**Issue by shuiping233** [revengenowstudio/YR_RN_Mission_Editor#25]
- 新地编似乎在处理路径点的时候并没有对路径点进行排序，以下是在我随机创建了一些路径点，有些是使用“用指定ID建立路径点”创建的
![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/c6010b51-63b7-41d3-962e-49f8390c32f7)
![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/30716907-96dd-4ad7-a29a-886bf55c8186)
- 保存地图后重新读取地图再进入“查找路径点”也是和保存前一样的乱序，
- 左边为旧地编保存的地图文本，右边为新地编保存的地图文本
![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/14b7237b-7c46-4661-a3db-75f291de5ffd)

![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/5c8043a7-4c92-43a0-be9e-414dac0c1e37)

**Comment by shuiping233** [comment]
- 测试环境： 29caa6b
- 测试条件：创建一张单人任务地图
- 测试结论：
    - 目前地编已确保对路径点增删后路径点列表一定有序
    - 删除路径点后，查找路径点列表中的元素不会随着消失而是被置空，在路径点标号未达到`100`时，`98`和`99`号路径点（可能比`99`大的路径点也）无法正常显示在查找路径点中显示
    - 下图中的地图只有`98`和`99`号路径点，
![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/973e1e67-02d7-4854-91aa-1d58c795be4e)

**Comment by Zero-Fanker** [comment]
> * 测试环境： [29caa6b](https://github.com/revengenowstudio/YR_RN_Mission_Editor/commit/29caa6b9d8ad2dc28e19a958678f01f1a03bd0fb)
> * 测试条件：创建一张单人任务地图
> * 测试结论：
>   
>   * 目前地编已确保对路径点增删后路径点列表一定有序
>   * 删除路径点后，查找路径点列表中的元素不会随着消失而是被置空，在路径点标号未达到`100`时，`98`和`99`号路径点（可能比`99`大的路径点也）无法正常显示在查找路径点中显示
>   * 下图中的地图只有`98`和`99`号路径点，
>     ![image](https://private-user-images.githubusercontent.com/49360196/340381186-973e1e67-02d7-4854-91aa-1d58c795be4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2NDI2NTIsIm5iZiI6MTcxODY0MjM1MiwicGF0aCI6Ii80OTM2MDE5Ni8zNDAzODExODYtOTczZTFlNjctMDJkNy00ODU0LTkxYWEtMWQ1OGM3OTViZTRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDE2MzkxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzNDkyNjI3MDZmNzc3N2NkZWEzOTVjYTE1OTRmYTJmNmI4N2YxNjIyYzFjMWVkMzVkOTQ3YWRjZDY4MzBmNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L7jjao7kHOg_D9-m8ijZXP-gMFnsJbqtMPfxUT1JZj0)

f5817e91ff6255d5a16239c0b95c57ac43dcc273 已调整

**Comment by shuiping233** [comment]
- 测试环境： f5817e91
- 测试条件：创建一张单人任务地图，创建一些路径点，然后删除几个路径点
- 测试结论：测试通过，在查找路径点的路径点列表中可以正常显示和查找`98`和`99`号路径点，且删除路径点后路径点列表中不再出现空元素；下图地图文本对比中，左旧右新，已确认地图文本中路径点标号是按照升序排序的

![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/dcce4ce9-e80b-45c3-a0ea-bff9ab0a0ba0)

![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/1895a16a-5255-4d17-bd1a-d6c303c652f5)
