### ISSUE TITLE
删除所属方（house）后，所属方下拉列表里仍然存在，但是细节参数为空

### ISSUE THREAD

**Issue by shuiping233** [revengenowstudio/YR_RN_Mission_Editor#27]
- 如题，点击删除所属方按钮之后，所属方列表里还存在理应该被删除的所属方，读取不到所属方内容说明所属方定义被删掉了，但是`[Houses]`列表应该没有清理掉这个所属方
![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/5e3a09db-461a-45e6-ae60-2e9f88ac3d69)

- 左边是删除所属方前的地图内容，右边是删除后的地图内容
![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/247237b9-5014-44a3-9117-d7a5f747f97f)
- 可见，删除所属方功能并没有处理`[Houses]`里应该被删除的`test1 House`
![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/c1ae7021-d34a-4d9c-80c6-a749fd629cac)

- 测试用例：创建一个所属方后，点击“删除所属方”按钮

**Comment by Zero-Fanker** [comment]
这个问题确定不是FA2以前就有的问题吗

**Comment by shuiping233** [comment]
> 这个问题确定不是FA2以前就有的问题吗

- 如果工头指的是 country，那确实旧版和新版地编都删不掉country，但是这个issue指的是在所属方窗口里里删除所属方没法删掉house。如果工头觉得有必要对country也一并删除的话，请提醒我开个新issue
![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/811870d4-d356-493c-b2c9-67ec95e2427e)
- 下图为旧版地编删除所属方（house）的行为：
![GIF103](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/b25387d5-9e82-429e-93eb-169d57d5f152)
- 下图为新版地编删除所属方的行为  0e7315b3 ：
![GIF103](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/c9d06336-ef50-47f2-ad14-e4b399b3bb4d)

**Comment by Zero-Fanker** [comment]
确认了，是没删干净，Houses这个里面仍然有记录

**Comment by shuiping233** [comment]
- 测试环境： a58d063
- 测试条件：创建一个所属方，删除一个所属方
- 测试结论：测试通过，现在删除所属方后，`Houses`列表中的对应所属方也会被删除了
