### ISSUE TITLE
特遣部队编辑器中无法正常处理和保存输入的单位类型（Unit type）和单位数量（Number of units）内容

### ISSUE THREAD

**Issue by shuiping233** [revengenowstudio/YR_RN_Mission_Editor#34]
- 如图所示，我的输入无法被地编应用，且被强制替换成某些固定值了：
![GIF90](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/112644c1-a57d-464a-9928-099b7724748e)
- 这是保存地图后的文本内容：
![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/e92d0cd0-068f-4e62-959e-2854689a24bd)
- 后续测试发现，若直接键盘输入内容至单位类型（Unit type）文本框中，保存地图后输入的内容会被正确保存，但是单位类型（Unit type）文本框内显示的内容依然会被强制显示成某些固定值
![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/76c807a1-b5b5-43f1-bc83-380b5c29fc75)
![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/3522b8b9-11b3-4cf8-9b88-3d23a1ab5c3e)

- 测试用例：创建一个特遣部队，对单位类型（Unit type）和单位数量（Number of units）进行任意修改

**Comment by Zero-Fanker** [comment]
关联 #32 的修复。提交：revengenowstudio/YR_RN_Mission_Editor/commit/9b2134c
