### ISSUE TITLE
特遣部队编辑器无法正确删除对应的单位元素

### ISSUE THREAD

**Issue by shuiping233** [revengenowstudio/YR_RN_Mission_Editor#35]
- 如图所示，不仅删除的不是选中的单位元素，而且删除全部元素后，总有一个元素无法显示和被选中且无法删除
![GIF91](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/4813c7f9-ecce-4521-9893-42e761dbd27b)
- 删除前保存的特遣部队文本内容：
![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/8ec6cba3-4daf-4a1f-8321-769654f98653)
- 删除后保存的特遣部队文本内容：
![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/2c6fa907-8cad-42f8-98f2-d76f28ceb908)

- 测试用例：创建一个特遣部队，添加几个单位元素，然后逐一使用`Units in task force:`下方的delete按钮删除

**Comment by Zero-Fanker** [comment]
调整过了。不过顺便观察下，是不是地编本来删成员的时候就是把最后一个往被删的那个位置去覆盖的？另外记得关注测一下最后一个成员被删掉，group和name设置成非空非默认值，例如group写3，然后试试会发生什么。

**Comment by shuiping233** [comment]
> 调整过了。不过顺便观察下，是不是地编本来删成员的时候就是把最后一个往被删的那个位置去覆盖的？另外记得关注测一下最后一个成员被删掉，group和name设置成非空非默认值，例如group写3，然后试试会发生什么。

- 关于旧地编删除特遣部队成员的情况，我确实观察到地编把当前特遣部队最后一个成员覆盖至需要被删除的成员位置来完成删除的现象，
![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/883d526c-51c2-4605-a55a-afa404e72974)
![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/66a6c140-80e5-40ea-8a67-a0761b8db55a)
- 而关于删除成员对特遣部队的`group`和`name`的影响，在旧地编的测试中发现删除成员对特遣部队的`group`和`name`都没有任何影响
![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/6c71645b-df4e-4ca9-9272-fc099a9afcca)
![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/101498b1-7929-4d09-b25f-a2cd5bb14790)


f9620f7 修复的测试结果：
- 特遣部队成员的`Number of units` `Unit type`展示的内容仍然不正确，且删除一个成员后另一个成员会显示为`missing`，地图文件保存后发现地图文件中只删除了某些成员（下图演示中我删除了`E1`和`E2`），而其他成员的序号和内容均未改变
- 除了第一个和第二个成员，第三个成员显示的`Number of units`和`Unit type`内容就是本应该第一个成员正确显示的内容，而第四个成员显示的`Number of units`和`Unit type`内容是第二个成员正确显示的内容，这是否能说明此问题可能是从特遣部队成员数组中读取某个成员时index不正确而造成的？
![GIF93](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/f5155621-6cee-476f-9a51-cd7a698e3482)
- 特遣部队原内容：
![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/8bd0ab30-e33b-445c-aee6-c959e1a0cd4f)

- 新地编删除两个成员（`E1`和`E2`）后保存的内容：
![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/915b8df3-9e2d-4d82-8b0f-150a96e466c2)

**Comment by shuiping233** [comment]
a73a2e4 修复的测试结果：
- 新地编已经可以正确删除对应的成员
![GIF94](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/557e0092-7d31-423d-b6dc-d8280f01e277)
![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/0f8714ca-81f9-4779-bef8-ac1b9fe527c9)
