### ISSUE TITLE
作战小队编辑器无法正确将勾选的特定配置保存至地图文件

### ISSUE THREAD

**Issue by shuiping233** [revengenowstudio/YR_RN_Mission_Editor#36]
- 全部复选框勾选后，保存地图文件
![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/cbda96c4-9eab-4b8b-ab84-0054fe7ce537)
- 地编重新读取刚刚保存的地图文件，发现部分复选框的设置没有生效
![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/b14a7b36-c4c3-41c1-9a07-bad745bc9737)
![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/a72fae6e-98a3-401e-97d4-b31b52d0e845)

- 第二次测试，删除了之前的作战小队并新建一个作战小队，只勾选了`Cargo plane `，然后保存
![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/76d525bc-3a97-4b0a-ae54-94f86615bd74)
- 重新读取地图，发现`Full` `Annoyance`却被勾选了，`Cargo plane `没有被勾选，而地图文本的内容也是`Full` `Annoyance` 为 `yes`
![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/eb11c31b-030f-40f5-bdf4-387cb1e6081d)
![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/b43cde27-0f75-43b7-9b64-70b847e50cc5)

- 测试用例1：创建一个作战小队，勾选所有的复选框，然后保存地图，地编重新读取地图
- 测试用例2：创建一个作战小队，勾选部分或者其中一个复选框，然后保存地图，地编重新读取地图

**Comment by shuiping233** [comment]
- 测试环境： 27332be3c673be20c49b4fad708b3bf8c404699a ，新建一张单人任务地图，启用 `准备标准所属方`以及`创建默认ai触发`
- 测试条件：在新建地图基础上，新建一个`作战小队`，先对`作战小队`中所有复选框全部取消勾选，然后保存地图，另外保存此状态的测试地图，再对每一个`作战小队`的复选框进行勾选测试，检查其地编实际操作结果。每次只勾选一个复选框并且与先前全部取消勾选状态的备份地图使用vsc进行内容对比。结果如下：

- 所有复选框均不勾选的情况下保存内容：
```
Loadable=no
Full=yes    # 这里不应该为yes
Annoyance=no
GuardSlower=no
Recruiter=no
Autocreate=no
Prebuild=no
Reinforce=no
Droppod=no
Whiner=no
LooseRecruit=no
Aggressive=no
Suicide=no

OnTransOnly=no
AvoidThreats=no
IonImmune=no
TransportsReturnOnUnload=no
AreTeamMembersRecruitable=no
IsBaseDefense=no
OnlyTargetHouseEnemy=no
UseTransportOrigin=no
```

- 以下为各复选框实际操作的属性列表，只列举了异常情况，正确情况无需列出

|勾选的复选框|实际操作的属性|
|-----------|-------------|
|Full|不操作任何属性|
|Guard slower|不操作任何属性|
|Recruiter|Annoyance|
|Carge plane|Annoyance|
|Aggressive|LooseRecruit|
|AvoidThreats|Reinforce|
|OnlyTargetHouseEnemy|IsBaseDefense|

**Comment by Zero-Fanker** [comment]
> * 测试环境： [27332be](https://github.com/revengenowstudio/YR_RN_Mission_Editor/commit/27332be3c673be20c49b4fad708b3bf8c404699a) ，新建一张单人任务地图，启用 `准备标准所属方`以及`创建默认ai触发`
> * 测试条件：在新建地图基础上，新建一个`作战小队`，先对`作战小队`中所有复选框全部取消勾选，然后保存地图，另外保存此状态的测试地图，再对每一个`作战小队`的复选框进行勾选测试，检查其地编实际操作结果。每次只勾选一个复选框并且与先前全部取消勾选状态的备份地图使用vsc进行内容对比。结果如下：
> * 所有复选框均不勾选的情况下保存内容：
> 
> ```
> Loadable=no
> Full=yes    # 这里不应该为yes
> Annoyance=no
> GuardSlower=no
> Recruiter=no
> Autocreate=no
> Prebuild=no
> Reinforce=no
> Droppod=no
> Whiner=no
> LooseRecruit=no
> Aggressive=no
> Suicide=no
> 
> OnTransOnly=no
> AvoidThreats=no
> IonImmune=no
> TransportsReturnOnUnload=no
> AreTeamMembersRecruitable=no
> IsBaseDefense=no
> OnlyTargetHouseEnemy=no
> UseTransportOrigin=no
> ```
> 
> * 以下为各复选框实际操作的属性列表，只列举了异常情况，正确情况无需列出
> 
> 勾选的复选框	实际操作的属性
> Full	不操作任何属性
> Guard slower	不操作任何属性
> Recruiter	Annoyance
> Carge plane	Annoyance
> Aggressive	LooseRecruit
> AvoidThreats	Reinforce
> OnlyTargetHouseEnemy	IsBaseDefense

证实，已修复

**Comment by shuiping233** [comment]
- 测试环境： 04cb11f6 ，新建一张单人任务地图，启用 `准备标准所属方`以及`创建默认ai触发`
- 测试条件：在新建地图基础上，新建一个`作战小队`，先对`作战小队`中所有复选框全部取消勾选，然后保存地图，另外保存此状态的测试地图，再对每一个`作战小队`的复选框进行勾选测试，检查其地编实际操作结果。每次只勾选一个复选框并且与先前全部取消勾选状态的备份地图使用vsc进行内容对比。
- 测试结论：测试通过，目前所有复选框描述内容与实际操作的属性均一致，且行为符合预期，结果如下：

- 以下为各复选框实际操作的属性列表  

|勾选的复选框|实际操作的属性|是否符合预期|
|-----------|-------------|-----------|
|Full|Full|✔️|
|Guard slower|GuardSlower|✔️|
|Recruiter|Recruiter|✔️|
|Carge plane|Droppod|✔️|
|Aggressive|Aggressive|✔️|
|AvoidThreats|AvoidThreats|✔️|
|OnlyTargetHouseEnemy|OnlyTargetHouseEnemy|✔️|
