### ISSUE TITLE
`游戏者位置`功能覆盖现有路径点后产生相同标号的路径点

### ISSUE THREAD

**Issue by shuiping233** [revengenowstudio/YR_RN_Mission_Editor#52]
- 测试环境： 12d4e2705
- 测试条件：新建一张地图，使用任一`游戏者位置`成员，并在地图上点击几次，或者长按滑动鼠标，然后保存地图
- 结论：`游戏者位置`功能不正常，使用此功能会覆盖掉已经存在的路径点且置其他路径点为0~7，由此产生相同标号的路径点
![GIF104](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/2b300e7f-9bd5-4533-af2d-017f746d66bb)

**Comment by Zero-Fanker** [comment]
覆盖本来就是合理的，位置1-8对应的就是路径点0-7。
问题在于会重复产生同一个序号的路径点

**Comment by shuiping233** [comment]
- 测试环境 ： v2.1.9
- 测试条件：创建一张单人任务地图和一张遭遇战地图，使用`游戏者位置`功能
- 结论：
  -  在旧版地编中，~~非0-7标号的路径点不会受到`游戏者位置`功能影响，且地图中不存在0-7路径点时，`游戏者位置`不会存在`游戏者`成员~~ 即使地图中存在0-7标号路径点，`游戏者位置`中也不会存在任何成员
![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/b71a5dfc-8e52-4019-b917-a79a2b7a7088)
![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/a46a24bf-f0c6-448d-904e-b541beaa7f0d)
  - 在新版地编中，创建一张单人任务地图，98和99号路径点会判定为`游戏者1`，并且操作`游戏者1`就是一起操作98和99号路径点，如果删除98和99号路径点，使用`游戏者1`也可以把两个路径点一起放置在地图中
![GIF105](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/9b53546b-4021-4d66-9ae5-b04d45c52c9c)
  - 在新版地编中，读取一张非8人图`sekigahara6.map`，`游戏者位置`也会出现8个成员
![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/960df846-e037-4254-87dd-8f9efb65f956)
  - 在新版地编中，使用`删除路径点`或者`删除游戏者位置`删除任意0-7号路径点，`游戏者位置`中成员并不发生任何变化
![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/c5854a4a-3433-4e57-92a1-51abcf916dcd)
  - 在新版地编中，使用`游戏者位置`已经可以正确覆盖游戏位置对应的路径点且不会产生重复路径点
  - 鉴于旧版地编中`游戏者位置`功能“不可用”，我需要确定预期效果来判断修复是否完成 @Zero-Fanker

**Comment by Zero-Fanker** [comment]
> * 测试环境 ： v2.1.9
> * 测试条件：创建一张单人任务地图和一张遭遇战地图，使用`游戏者位置`功能
> * 结论：
>   
>   * 在旧版地编中，~非0-7标号的路径点不会受到`游戏者位置`功能影响，且地图中不存在0-7路径点时，`游戏者位置`不会存在`游戏者`成员~ 即使地图中存在0-7标号路径点，`游戏者位置`中也不会存在任何成员
>     ![image](https://private-user-images.githubusercontent.com/49360196/342189619-b71a5dfc-8e52-4019-b917-a79a2b7a7088.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyOTE2MzMsIm5iZiI6MTcxOTI5MTMzMywicGF0aCI6Ii80OTM2MDE5Ni8zNDIxODk2MTktYjcxYTVkZmMtOGU1Mi00MDE5LWI5MTctYTc5YTJiN2E3MDg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDA0NTUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0ZjIwY2VmNWEyZDUyNjM2NzEyNGU5OGI5ZTcxMzYyM2VhNWUxNTdhOTA0MDg0NjZhYWY5Y2ZiZjMzNDc1NTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CbDogZ4w0mQqO4U5CsY3kLx5XXyMvU-ijPblhFnlE98)
>     ![image](https://private-user-images.githubusercontent.com/49360196/342191052-a46a24bf-f0c6-448d-904e-b541beaa7f0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyOTE2MzMsIm5iZiI6MTcxOTI5MTMzMywicGF0aCI6Ii80OTM2MDE5Ni8zNDIxOTEwNTItYTQ2YTI0YmYtZjBjNi00NDhkLTkwNGUtYjU0MWJlYWE3ZjBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDA0NTUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2OWIxZTQyNGM3ZDZiYTRjY2E1NDU4ZTk0NDk4NTI4NmZjNzJhYjE5NTRhYWYwYjc3ZGJjNWE5ZGRhMDU3ZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bJGVY2agWDc8LUdEYJYFQQ0aim0dsakZkxY599yKTqo)
>   * 在新版地编中，创建一张单人任务地图，98和99号路径点会判定为`游戏者1`，并且操作`游戏者1`就是一起操作98和99号路径点，如果删除98和99号路径点，使用`游戏者1`也可以把两个路径点一起放置在地图中
>     ![GIF105](https://private-user-images.githubusercontent.com/49360196/342190082-9b53546b-4021-4d66-9ae5-b04d45c52c9c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyOTE2MzMsIm5iZiI6MTcxOTI5MTMzMywicGF0aCI6Ii80OTM2MDE5Ni8zNDIxOTAwODItOWI1MzU0NmItNDAyMS00ZDY2LTlhZTUtYjA0ZDQ1YzUyYzljLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDA0NTUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2NmIwNWFlMGJiMGIyNDY5NDA4MmRiZDcxOTU3OGQ2MDkwNzYyZDZkM2Y2NzA1YjY1MmI2YTE2YzIwYWMxY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-7Y3cuUI8Eo2Ljl1QdP7RDKGF3A6GkG4a9g4wB-8WWg)
>           
>             [
>               
>             
>                 ![GIF105](https://private-user-images.githubusercontent.com/49360196/342190082-9b53546b-4021-4d66-9ae5-b04d45c52c9c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyOTE2MzMsIm5iZiI6MTcxOTI5MTMzMywicGF0aCI6Ii80OTM2MDE5Ni8zNDIxOTAwODItOWI1MzU0NmItNDAyMS00ZDY2LTlhZTUtYjA0ZDQ1YzUyYzljLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDA0NTUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2NmIwNWFlMGJiMGIyNDY5NDA4MmRiZDcxOTU3OGQ2MDkwNzYyZDZkM2Y2NzA1YjY1MmI2YTE2YzIwYWMxY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-7Y3cuUI8Eo2Ljl1QdP7RDKGF3A6GkG4a9g4wB-8WWg)
>               ](https://private-user-images.githubusercontent.com/49360196/342190082-9b53546b-4021-4d66-9ae5-b04d45c52c9c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyOTE2MzMsIm5iZiI6MTcxOTI5MTMzMywicGF0aCI6Ii80OTM2MDE5Ni8zNDIxOTAwODItOWI1MzU0NmItNDAyMS00ZDY2LTlhZTUtYjA0ZDQ1YzUyYzljLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDA0NTUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2NmIwNWFlMGJiMGIyNDY5NDA4MmRiZDcxOTU3OGQ2MDkwNzYyZDZkM2Y2NzA1YjY1MmI2YTE2YzIwYWMxY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-7Y3cuUI8Eo2Ljl1QdP7RDKGF3A6GkG4a9g4wB-8WWg)
>             
>             
>               
>                 
>                   
>                 
>                 
>                   
>                   
>                 
>               
>               [
>                 
>                   
>                 
>               ](https://private-user-images.githubusercontent.com/49360196/342190082-9b53546b-4021-4d66-9ae5-b04d45c52c9c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyOTE2MzMsIm5iZiI6MTcxOTI5MTMzMywicGF0aCI6Ii80OTM2MDE5Ni8zNDIxOTAwODItOWI1MzU0NmItNDAyMS00ZDY2LTlhZTUtYjA0ZDQ1YzUyYzljLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDA0NTUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2NmIwNWFlMGJiMGIyNDY5NDA4MmRiZDcxOTU3OGQ2MDkwNzYyZDZkM2Y2NzA1YjY1MmI2YTE2YzIwYWMxY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-7Y3cuUI8Eo2Ljl1QdP7RDKGF3A6GkG4a9g4wB-8WWg)
>   * 在新版地编中，读取一张非8人图`sekigahara6.map`，`游戏者位置`也会出现8个成员
>     ![image](https://private-user-images.githubusercontent.com/49360196/342192542-960df846-e037-4254-87dd-8f9efb65f956.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyOTE2MzMsIm5iZiI6MTcxOTI5MTMzMywicGF0aCI6Ii80OTM2MDE5Ni8zNDIxOTI1NDItOTYwZGY4NDYtZTAzNy00MjU0LTg3ZGQtOGY5ZWZiNjVmOTU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDA0NTUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmMGQ3NTliN2Q5ZTg0OTg0ZWFhZjNjODQ5MWYyMzYxZDRlOTRhZTU5NTVkNWZjYzU2MjA2NGU5MzU1YWNlMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Nr-6HPjFeWUuNeHt1lfbaGA7AgtkRnt3QtfXidsJjvU)
>   * 在新版地编中，使用`删除路径点`或者`删除游戏者位置`删除任意0-7号路径点，`游戏者位置`中成员并不发生任何变化
>     ![image](https://private-user-images.githubusercontent.com/49360196/342193180-c5854a4a-3433-4e57-92a1-51abcf916dcd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyOTE2MzMsIm5iZiI6MTcxOTI5MTMzMywicGF0aCI6Ii80OTM2MDE5Ni8zNDIxOTMxODAtYzU4NTRhNGEtMzQzMy00ZTU3LTkyYTEtNTFhYmNmOTE2ZGNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDA0NTUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhODQ0OWRkNzRlNGViNWFkZDdmZTY1ZDhkMDk4NDg1YjI3NWQzOTAyNmJlYjM1MjQzOWViZTNhN2U3M2QyMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Mdhu_X9er7m14Vd5KlyQyH-suHWLGgU7K4xeS3FANVo)
>   * 在新版地编中，使用`游戏者位置`已经可以正确覆盖游戏位置对应的路径点且不会产生重复路径点
>   * 鉴于旧版地编中`游戏者位置`功能“不可用”，我需要确定预期效果来判断修复是否完成 @Zero-Fanker

事实上“游戏者位置”在原版就是这样的。你想测试很简单，RN旧版地编里有一个“实在没办法再运行我.exe”

**Comment by shuiping233** [comment]
- 测试环境： v2.1.9
- 结论：
  - 旧版地编的`游戏者位置`行为与新版地编现在的`游戏者位置`行为一致
  - 单人任务中，操作`游戏者1`会移动98号和99号路径点，因为玩家进入单人任务时，摄像机视角会居中到两个路径点的位置
  - 遭遇战地图中，`游戏者位置`会存在8个元素加上一个删除游戏者位置
  - 测试通过
