### ISSUE TITLE
保存地图窗口-设置地图最少玩家数功能

### ISSUE THREAD

**Issue by shuiping233** [revengenowstudio/YR_RN_Mission_Editor#70]
![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/5358af50-fec6-413e-ab9c-4fe958e3bc2f)

**Comment by Zero-Fanker** [comment]
~~这个晚点放在基本设置里实现~~
我改变主意了，我还是沿用原来的做法了。

**Comment by shuiping233** [comment]
目前地编实现的效果如图：
![image](https://github.com/user-attachments/assets/76317930-b401-4db8-9480-f41c44546a54)

稍微问一下，最少玩家数默认值是0，这是符合预期的么？
