### ISSUE TITLE
动作脚本编辑窗口有时无法正确转换`附加参数`的值

### ISSUE THREAD

**Issue by shuiping233** [revengenowstudio/YR_RN_Mission_Editor#76]
- 测试环境： 1f2d77f711
- 测试条件： 创建一个动作脚本，脚本中新建一个行为且行为类型为46，然后在`附加参数`中填写大于`0`的数值
- 测试结论： 
  -  一个脚本行为保存在地图文件后，实际上只有两个元素，一个是行为id，一个是对应行为所需的值，而某些行为存在`附加参数`，旧版地编在保存`附加参数`时实际保存了 `附加参数的值 * 65536 + 另一个所需的值` 运算后的结果
  - 新地编在保存需要`附加参数`（例如行为46）的动作脚本时，与旧地编行为一致，符合预期
  - 新地编在读取需要`附加参数`（例如行为46）的动作脚本时，未进行 `附加参数的值 * 65536 + 另一个所需的值`  公式逆运算，直接将未经过运算的值显示在一个文本框中
  - 下图为按照测试条件进行操作后，地编重新读取地图的结果

![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/37af59e4-14e8-40eb-b138-407504414441)
![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/a5e8dd2d-b67f-4b2e-8bb7-39b6bef61bea)

 - #55 的测试中遗漏了这个测试

**Comment by shuiping233** [comment]
- 测试环境： a58d063
- 测试条件： 打开小队脚本编辑器，然后选中一个存在`附加参数`的脚本行为，重新读取地图
- 测试结论：如下视频所示，只是文本框显示的内容存在问题，保存到地图文件中的值是符合预期的

https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/ec001ac4-25aa-4121-ae3b-d849d5d46197

**Comment by shuiping233** [comment]
> * 测试环境： [a58d063](https://github.com/revengenowstudio/YR_RN_Mission_Editor/commit/a58d063b2271baa24cc163d19e694d2766dab587)
> * 测试条件： 打开小队脚本编辑器，然后选中一个存在`附加参数`的脚本行为，重新读取地图
> * 测试结论：如下视频所示，只是文本框显示的内容存在问题，保存到地图文件中的值是符合预期的
> 
>  2024-07-04.18-48-40.mp4
- 补充一个测试条件：创建一张单人任务地图，打开小队脚本编辑器，创建一个小队脚本，往小队脚本添加一个行为，行为类型为46，`建筑`文本框值为`2`,`附加参数`文本框值为`2`，保存地图，此时使用地编重新打开刚刚保存的地图，再进入刚刚创建的小队脚本查看`建筑`文本框的值

**Comment by Zero-Fanker** [comment]
复现的条件是，重复选择同一个类型的脚本动作类型。我有个函数调用被我调整了一下顺序，导致了这个问题。

**Comment by shuiping233** [comment]
- 测试环境： 0061df657
- 测试条件： https://github.com/revengenowstudio/YR_RN_Mission_Editor/issues/76#issuecomment-2208856939
- 测试结论： 测试通过，现在`附加参数`的值可以被正常转换和在文本框中显示了，已经无法再次复现此issue描述的问题了
