### ISSUE TITLE
所属方编辑器创建新所属方默认添加盟友`全球安全防禦理事會`

### ISSUE THREAD

**Issue by shuiping233** [revengenowstudio/YR_RN_Mission_Editor#77]
- 测试环境： 834d561450
- 测试条件：创建一个新所属方
- 建议：新建地图默认不会创建`全球安全防禦理事會`（GDI）所属方，而默认创建的所属方的盟友关系中也不存在`全球安全防禦理事會`，所以建议创建新所属方时不添加`全球安全防禦理事會`的盟友关系

![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/aa2b1d0e-9270-4dce-bae3-8b4014258ae8)

![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/f9f9659a-906b-4aed-8230-ca9c8363792e)

**Comment by Zero-Fanker** [comment]
这问题应该是一个FA2的遗留问题，可能早年的patch把它修了，但是正常来说没做任何patch的FA2应该也会有这个问题。

**Comment by shuiping233** [comment]
> 这问题应该是一个FA2的遗留问题，可能早年的patch把它修了，但是正常来说没做任何patch的FA2应该也会有这个问题。

旧版地编实际上也有这个问题，我忘记强调了）

**Comment by shuiping233** [comment]
- 测试环境： 0061df65
- 测试条件： 创建一个新所属方
- 测试结论： 测试通过，现在新建的所属方不再默认添加`全球安全防禦理事會`（GDI）所属方作为盟友了
![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/c6e164bb-8a2c-4e8f-b7bf-6bd24e9743f4)
![image](https://github.com/revengenowstudio/YR_RN_Mission_Editor/assets/49360196/816d27db-beba-4935-9714-d69722d346a7)
