### ISSUE TITLE
建筑和飞行器默认设置的问题

### ISSUE THREAD

**Issue by handama** [revengenowstudio/YR_RN_Mission_Editor#98]
<img width="338" alt="Snipaste_2024-08-07_23-08-37" src="https://github.com/user-attachments/assets/5c38a65b-4328-45b0-a8ad-13f0f345468c">
<img width="314" alt="Snipaste_2024-08-07_23-08-27" src="https://github.com/user-attachments/assets/9837aeb2-585e-45f9-bf25-783e179f5382">

飞机的group默认是0，也就是编号1，应该为-1  
建筑的方向默认是64，导致飞机停靠的方向也是64，应该改为0

**Comment by handama** [comment]
飞机小组还没改啊阿伟，应该是flag2
![Screenshot_2024-10-01-08-58-44-740_com android chrome](https://github.com/user-attachments/assets/d95035eb-ce8c-46e8-9c6b-ecb0c5a8c25d)

**Comment by Zero-Fanker** [comment]
> 飞机小组还没改啊阿伟，应该是flag2 ![Screenshot_2024-10-01-08-58-44-740_com android chrome](https://private-user-images.githubusercontent.com/55939089/372279721-d95035eb-ce8c-46e8-9c6b-ecb0c5a8c25d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4Mjc4NzYsIm5iZiI6MTcyNzgyNzU3NiwicGF0aCI6Ii81NTkzOTA4OS8zNzIyNzk3MjEtZDk1MDM1ZWItY2U4Yy00NmU4LTljNmItZWNiMGM1YThjMjVkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDAwMDYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmNTA0NzRiMzVjYmVmYTZjYzNlOWU3NjVkZjcxOThmNjM3YzkyMGEyYWE5ZDkyMWQxMzg3ZDVmNzVhZDU2ZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1NzeFBWcMlYUkXpKOHbQo4n6dh4jeZaxBm9KkeoXJbM)

你也可以直接提PR啊= =
